#!/bin/bash
#pulseaudio script

source ~/IOT-Project/vol.txt
vol=$var
killall pulseaudio
pulseaudio -D
#restart pulseaudio, allows to recognize bluetooth in as audio
sudo amixer cset numid=3 1
#set audio out as 3.5mm jack
sudo amixer sset PCM,0 $var%
